// <auto-generated by UnityToolsHub />
#if UNITY_EDITOR
using UnityEditor;
internal static class UnityToolsHubGeneratedMenu
{
    [MenuItem("UnityToolsHub/最近使用/项目打包", false, -80)]
    private static void Open0() => UnityToolsHub.OpenRegisteredTool("ProjectBuilder");
    [MenuItem("UnityToolsHub/最近使用/富文本编辑器(网页版)", false, -79)]
    private static void Open1() => UnityToolsHub.OpenRegisteredTool("RichTextEditorWebLauncher");
    [MenuItem("UnityToolsHub/最近使用/Using 管理", false, -78)]
    private static void Open2() => UnityToolsHub.OpenRegisteredTool("UnityFramework.UsingManager");
    [MenuItem("UnityToolsHub/最近使用/自定义宏管理", false, -77)]
    private static void Open3() => UnityToolsHub.OpenRegisteredTool("ScriptingDefineManagerWindow");
    [MenuItem("UnityToolsHub/最近使用/帧动画创建工具", false, -76)]
    private static void Open4() => UnityToolsHub.OpenRegisteredTool("FrameAnimationCreator");
    [MenuItem("UnityToolsHub/最常使用/Git 包切换器", false, -60)]
    private static void Open5() => UnityToolsHub.OpenRegisteredTool("GitPackageSwitcher");
    [MenuItem("UnityToolsHub/最常使用/帧动画创建工具", false, -59)]
    private static void Open6() => UnityToolsHub.OpenRegisteredTool("FrameAnimationCreator");
    [MenuItem("UnityToolsHub/最常使用/视频首帧导出", false, -58)]
    private static void Open7() => UnityToolsHub.OpenRegisteredTool("VideoFirstFrameExporter");
    [MenuItem("UnityToolsHub/最常使用/样式模板", false, -57)]
    private static void Open8() => UnityToolsHub.OpenRegisteredTool("StyleShowcase");
    [MenuItem("UnityToolsHub/最常使用/Texture Color Bleed Window", false, -56)]
    private static void Open9() => UnityToolsHub.OpenRegisteredTool("SleepyCobalt.Tools.TextureTools.TextureColorBleedWindow");
}
#endif
